version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    environment:
      - PUID=1011
      - PGID=1011
      - TZ=America/Chicago
    volumes:
      - /opt/pihole/config:/etc/pihole
      - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
